### ISSUE TITLE
Error: Cannot find module 'meow'

### ISSUE THREAD

**Issue by tareefdev** [skt-t1-byungi/femdown#1]
I use node 10.17

````
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'meow'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/tareef/.nvm/versions/node/v10.17.0/lib/node_modules/femdown/lib/cli.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
````

**Comment by skt-t1-byungi** [comment]
Thanks. It is solved.
